modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
modId = "caffeineaddictmode"
version = "1.0.0"
displayName = "Caffeine Addict Mode"
description = '''
Simple caffeine-themed Minecraft mod.
'''
